Learn_templates/Learn_templates/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('baseapp/',include('basic_app.urls')),
]

Learn_templates/basic_app/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path
from basic_app import views

app_name = 'baseapp'
urlpatterns = [
    path('relative/',views.relative,name="relative"),
    path('other',views.other,name="other"),
]

Learn_templates/basic_app/models.py
from django.db import models

# Create your models here.

Learn_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basicapp/index.html',context_dict)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative.html')

Learn_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE PAGE</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-default navbar static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index'%}">Navbar</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'baseapp:other'%}">other</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>



</body>

</html>

Learn_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
{% block body_block %}
<h1>This is a index pages</h1>
<h2>This is inside block</h2>
{% comment %} <h1>{{ text |upper }}</h1> {% endcomment %}
<h1>{{ text | cut:'world' }}</h1>
<h1>{{ number | add:"99"}}</h1>

{% endblock %}
    

Learn_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
{% block body_block %}
<h1>this is other pages!</h1>
<h2>this is examplae to the templates inheritase</h2>
{% endblock  %}
    

Learn_templates/templates/basicapp/relative.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>relative.html</title>
</head>
<body>
    <h1>this is a relative page</h1>
    <a href="{% url 'baseapp:other'%}">The other pages</a>
    <a href="{% url 'admin:index'%}">this is admin pages</a>
    <a href="{% url 'index'%}">Link to index</a>
    
</body>
</html>